## Functions for efficiently computing the inverse of
## square matrices. The makeCacheMatrix function
## generates a special matrix wrapper that allows
## cacheSolve to determine whether or not the contained
## matrix's inverse has already been computed, thus avoid
## work.



## Generate a matrix suitable for use with the
## cacheSolve matrix inversion function.
##
## The returned matrix carries a flag that describes
## whether or not the inverse was previously computed
## so that redundant calls to cacheSolve avoid
## unneccessary work.

makeCacheMatrix <- function(x = matrix())
{
  inv <- NULL
  set <- function(y)
  {
    x <<- y
    inv <<- NULL
  }
  
  get <- function()
  {
    x
  }
  
  setInverse <- function(inverse)
  {
    inv <<- inverse
  }
  
  getInverse <- function()
  {
    inv
  }
  
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## Compute the inverse of an invertible square matrix.
## This function requires the input matrix to have
## been generated by makeCacheMatrix() (see above).
##
## cacheSolve will attempt to avoid recomputing
## the inverse by first checking if it has already done
## so. Otherwise, the inverse will be computed and stored
## to prevent future recomputation.

cacheSolve <- function(x, ...)
{
    ## Return a matrix that is the inverse of 'x'
    inverse <- x$getInverse()
    
    if (!is.null(inverse))
    {
      message("getting cached data")
      return(inverse)
    }

    inverse <- solve(x$get(), ...)
    x$setInverse(inverse)
    
    inverse
}
